### ISSUE TITLE
Submit Milestone 1

### ISSUE THREAD

**Issue by iamMoid** [UBC-MDS/Collision_Prediction#16]

**Comment by gn385x** [comment]
For milestone 1, I will be the proof-reader. Once all other issues are resolved, I will go over everything for one last time, submit to Canvas, and close this issue.

**Comment by danfke** [comment]
Just to summarize what needs to be done for submission: Copy-paste the contract into canvas, include URL of project repo in submission on canvas, create a release and name it 0.0.1 and include the URL of this release on canvas.

**Comment by gn385x** [comment]
Guys, should we put tag to be v0.0.1 when creating the release?
<img width="746" alt="Screen Shot 2021-11-21 at 9 57 10 AM" src="https://user-images.githubusercontent.com/94651544/142773457-d7838948-e26b-472f-90df-aa950ff8ae5b.png">

**Comment by iamMoid** [comment]
![Screenshot_20211121-104023_Chrome](https://user-images.githubusercontent.com/8488763/142774782-b4e2a33c-274b-4912-a131-26ce4075a132.jpg)
v0.0.1 it is.

**Comment by gn385x** [comment]
Hey yall, I just finished proof-reading all of our documents and scripts. All look amazing so I went ahead and submit the following to Canvas:

1. [URL of project repo](https://github.com/UBC-MDS/Collision_Prediction)
2. [URL of the release](https://github.com/UBC-MDS/Collision_Prediction/releases/tag/v0.0.1)
3. Team work contract (copy and paste from [here](https://docs.google.com/document/d/1S7HH-_QuHJio7NkWvpinbsBP1YQfwUfCw5RA3tFaIek/edit))

Great efforts and collaboration, guys! Go team!
