### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by danfke** [UBC-MDS/Collision_Prediction#17]
We need a directory structure. I'm thinking empty data folder, src folder containing the download script and EDA, and empty doc folder. Either that or we just create the src folder now and create new folders as we need them (this might make more sense). If you guys agree I can create the src folder on my pull request and move the download script in, and LG can make the src folder on her pull request and move the EDA in.

**Comment by danfke** [comment]
Nevermind it may be a bad idea to create the folders separately, I don't want to mess with git somehow, let's just merge everything and create them afterwards

**Comment by SiqiTao** [comment]
To be honest, I was about to mention this too, I think we are start working on the structure later on?

**Comment by iamMoid** [comment]
We can create the folder structure directly in the main repo i suppose.
