### ISSUE TITLE
Script 4 - Perform ML analysis

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/Collision_Prediction#22]
**Description**: A fourth script that reads the data from the second script, performs some statistical or machine learning analysis and summarizes the results as a figure(s) and a table(s). These should be written to files. This should take two arguments:

- a path/filename pointing to the data
- a path/filename prefix where to write the figure(s)/table(s) to and what to call it (e.g., results/this_analysis)

**Owner**: @SiqiTao 

**1st Reviewer**: @iamMoid

**Comment by iamMoid** [comment]
Once the model is ready, you need to save it as a pickle file. See the example below:

https://github.ubc.ca/mds-2021-22/DSCI_522_dsci-workflows_students/issues/24

**Comment by SiqiTao** [comment]
> Once the model is ready, you need to save it as a pickle file. See the example below:
> 
> https://github.ubc.ca/mds-2021-22/DSCI_522_dsci-workflows_students/issues/24

Already did, thanks for heads-up!
