### ISSUE TITLE
Script 5 - Literate code document 

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/Collision_Prediction#23]
**Description**: A fifth script: an .Rmd or .ipynb files that presents the key useful (not all!) exploratory data analysis as well as the statistical summaries and figures in a little report. There should be a written narrative in this document that introduces and justifies your question, introduces the data set, presents the findings/results, and interprets the findings/results in context of the question. Some critique of the analysis is also expected (limitations, assumptions, etc) and a statement of future directions (what would you do next if you had more time to work on this). The report is expected to be 1-2 written pages (excluding figures, tables and references). You are expected to have a reference section and cite 2-3 external sources (data source can be one of these citations) in addition to citing the programming languages and packages used. Yes, you need to cite the programming languages and packages used in your project. You will learn how to do this in lecture.

**Owner**: @iamMoid 

**1st Reviewer**: @gn385x

**Comment by iamMoid** [comment]
I am planning to include the following topics in our report:

1. Introduction
2. Analysis
2. a. Data
2. b. Model
3. Results
4. Conclusions
5. References

Let me know if we need to include/modify topics.
