### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/Collision_Prediction#25]
Update the README.md file to thoroughly explain the project in a short summary. 

Some suggested points to include:  

- Motivation
- Research question
- How to run the data analysis (which order scripts are run in, what expected inputs are, etc.)
- How to reproducibly run all scripts from top to bottom, including the arguments that need to be provided to each script
- Software dependencies for the analysis (or if using conda, point to the environment.yml file)

**Comment by iamMoid** [comment]
I am planning to include the following topics in our report:
1. Introduction
2. Analysis
   - Data
   - Model
3. Results
4. Conclusions
5. References

Let me know if we need to include/modify topics.

**Comment by gn385x** [comment]
@iamMoid What report are you talking about? I think we can use the example README.md as a guideline - [here](https://github.com/ttimbers/breast_cancer_predictor/blob/v2.0/README.md). 

The outline of the example README:

- [x] About -> We can use the README from Milestone 1 for this section.
- [x] Report -> We need to link the final report (Moid's script) here.
- [x] Usage -> We need to list out the usage from all of our scripts in order. I think following Tiff's example is good. 
- [x] Dependencies -> We need to use environment.yaml file to fill in this section. I think following Tiff's example is good. 
- [x] License -> Which license we need to specify??
- [x] References -> Which references we need to specify??

**Comment by danfke** [comment]
Ah dangit if it has references that means I have to make it on Rmd lol

**Comment by danfke** [comment]
References to our depedencies and dataset I think. License is the MIT license

**Comment by gn385x** [comment]
> References to our depedencies and dataset I think. License is the MIT license

ok!!

**Comment by iamMoid** [comment]
I was talking about the final report with the results on which I am working on.

**Comment by gn385x** [comment]
> I was talking about the final report with the results on which I am working on.

then can you move that comment to `script 5` issue so that we are not confusing the final report with the README file in this issue? thanks!

**Comment by danfke** [comment]
Alright so we need the results to finish the about section of the README. I need information on the R packages and stuff used to create the report to finish the dependencies.

**Comment by danfke** [comment]
Moid when everything is done can you write the rest of the README about section and put the required R packages in the dependencies?

**Comment by danfke** [comment]
Also update the link to the final report

**Comment by danfke** [comment]
The R packages still need to be put into the README

**Comment by iamMoid** [comment]
We also need to add the make commands under the 'Usage' section that can be used to execute end-to-end.
