### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by danfke** [UBC-MDS/Collision_Prediction#26]
Hi, please talk about dependencies we should delete or add to the environment here.

**Comment by danfke** [comment]
We definitely won't need nltk or spacy because we won't be doing NLP

**Comment by danfke** [comment]
We need to specify a python version?

**Comment by danfke** [comment]
Need altair saver

**Comment by danfke** [comment]
Need docopt

**Comment by iamMoid** [comment]
Need to include: pandas, scikit-learn

**Comment by danfke** [comment]
Updated environment file is now in my pull request. Once it is approved we need to make sure all scripts are compatible with it
