### ISSUE TITLE
EDA on NCDB data

### ISSUE THREAD

**Issue by iamMoid** [UBC-MDS/Collision_Prediction#3]
Perform EDA on National Collision data using Altair

**Comment by danfke** [comment]
EDA Checklist

1. Formulate a question.
2. Read in data.
3. Check the packaging. - Check number of rows, columns. Make sure they match the original data. Check .info() and .describe()
4. Look at top and bottom of the data. Make sure everything is properly formatted and is there, using .head() and .tail().
5. Check your n’s. Basically just check if the number of examples make sense.
6. Validate with at least one external data source. Can be as simple as checking against a single number (some external count of car accidents or fatalities in Canada during 2017?)
7. Make a plot. Sets expectations for what the data should look like. Once we have a good understanding of the data and our question, making a plot is a good way to see how the data matches our expectations.
8. Try the easy solution first (always be ready to challenge the solution). Start from a simple question?? I don’t completely understand what this means from the context of our project.
9. Follow-up questions. Do we have the right data? Do we need other data (eg other years)? Do we have the right question?


“The goal of exploratory data analysis is to get you thinking about your data and reasoning about your question. At this point, we can refine our question or collect new data, all in an iterative process to get at the truth.”
Excerpt From: Roger D. Peng and Elizabeth Matsui. “The Art of Data Science.” Apple Books.

**Comment by danfke** [comment]
EDA
-We have huge class imbalance
-Switch features that are numeric but should be categorical (possibly later)
-Need to replace all N, U, X with NA (possibly in later weeks)
-Rough EDA this week, later we will do more in-depth EDA
-Facet plots by target True and target False because of the class imbalance

**Comment by danfke** [comment]
Hey LG can you add `alt.renderers.enable(“mimetype”) ` to the beginning of the EDA so we can see the plots on github? Also can you add the .info() and .describe() tables of the training data?

**Comment by gn385x** [comment]
Hey Daniel, I added your suggestions in the pull request that I just created.

**Comment by gn385x** [comment]
Once EDA is well reviewed and good to go, I will create a PDF version of it, and close this issue.
