### ISSUE TITLE
Features to Include

### ISSUE THREAD

**Issue by danfke** [UBC-MDS/Collision_Prediction#31]
There are too many features in the model and it causes Jupyter to crash when trying to fit them. We need to decide which ones to get rid of and which ones to keep

**Comment by danfke** [comment]
Update: Discovered that there were a few more irrelevant features, so I deleted them, and now the model seems to work… It is very slow though so we can still preselect features using EDA

**Comment by danfke** [comment]
Nevermind theres too many features for sure, hyperparameter optimization takes forever

**Comment by danfke** [comment]
It's sort of hard to pick the best features. How about we all try to pick our top 10.

**Comment by iamMoid** [comment]
V_TYPE, V_YEAR are good features as the distribution of the bars for Fatality=False and Fatality=True shows a difference.

**Comment by danfke** [comment]
I've picked 6 that seem relevant.
-C_CONF
-C_HOUR
-C_TRAF
-P_AGE
-V_YEAR
-P_SAFE

**Comment by danfke** [comment]
If you guys agree with these, we need 4 more.

**Comment by iamMoid** [comment]
C_RALN is a good feature as well

**Comment by danfke** [comment]
Maybe we should just include the ones from our subquestions, road type, weather, time of year

**Comment by iamMoid** [comment]
Yes - those 5 plus 5 additional - 10 sounds like a good number. If the model still crashes then we will go down to 5.

**Comment by iamMoid** [comment]
Let us do:
-C_MNTH
-C_RCFG
-C_WTHR
-P_AGE
-V_TYPE
+
-C_CONF
-C_HOUR
-C_TRAF
-V_YEAR
-P_SAFE

**Comment by danfke** [comment]
Alright seems like we have our ten, @SiqiTao , @gn385x any thoughts?

**Comment by gn385x** [comment]
Just look at the EDA graphs of those, agree with the selection!

**Comment by SiqiTao** [comment]
10 sounds reasonable for me, but will we need some solid work in the report to show how we made the choice?

**Comment by danfke** [comment]
Can just reference our original sub questions and the EDA we performed

**Comment by danfke** [comment]
So we are including all features because of performance increases after I used RandomUnderSampler for the model

**Comment by danfke** [comment]
Now we will just rely on the feature selector to pick the features
