### ISSUE TITLE
Address feedback from TAs

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/Collision_Prediction#43]
Feedback from milestone 1:

- [x] The license should be copyrighted to your names not MDS.
- [x] Interesting question, don't need to go so far with 5 different models, keep things simple and clear.
- [x] The proposal should be in the README.md.
- [x] The download script should include a comment to explain what kind of exception you are expecting to catch.
- [x] Why did you choose the figures you did? 
- [x] What is your interpretation of the preliminary analysis/ EDA? 
- [x] Do any predictors stand out as useful? 
- [x] Is there a class imbalance that needs to be taken into account?
- [x] Be sure to use git mv to move files so that the changes are tracked.

**Comment by gn385x** [comment]
@SiqiTao hey Doris, could you address this feedback of the download script: "The download script should include a comment to explain what kind of exception you are expecting to catch." Thank you!

**Comment by gn385x** [comment]
Questions to check with instructors/ TAs:

- [x] Do we need to render EDA report (example is a markdown document)?
- [x] What to do with proposal at this stage?
- [x] Are we expecting feedbacks for milestone 2 soon?

**Comment by gn385x** [comment]
Additional improvement suggestions from Florencia during lab:

- [x] Code of conduct should include an email.
- [x] Figures should have captions.

**Comment by SiqiTao** [comment]
> could you address this feedback of the download script:

Yes!

**Comment by gn385x** [comment]
@danfke will add a link to the proposal in the README.md.

**Comment by gn385x** [comment]
@gn385x finished addressing all feedbacks for EDA. @iamMoid merged it.

**Comment by gn385x** [comment]
> Questions to check with instructors/ TAs:
> 
> * [x]  Do we need to render EDA report (example is a markdown document)?
> * [x]  What to do with proposal at this stage?
> * [x]  Are we expecting feedbacks for milestone 2 soon?

1. Pushing .ipynb to GitHub will render itself. 
2. We will add proposal to README.md.
3. Feedback for milestone 2 will come next week.
