### ISSUE TITLE
Create Makefile

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/Collision_Prediction#44]
Write a Makefile (literally called Makefile) to act as a driver script to rule them all. This script should run the others in sequence, hard coding in the appropriate arguments. This script should:

- [x] Live in the project’s root directory and be named Makefile
- [x] Be well documented (using the project README and comments inside the Makefile to explain what it does and how to use it)
- [x] Have a all: target so that you can easily run the entire analysis from top to bottom by running make all at the command line
- [x] Have a clean: target so that you can easily “undo” your analysis by running make clean at the command line

**Comment by iamMoid** [comment]
The Makefile may need slight modifications to the rules based on recent updates to the other scripts. Also need to add descriptions for each rule in the Makefile.
