### ISSUE TITLE
Meeting Notes for Milestone 3

### ISSUE THREAD

**Issue by danfke** [UBC-MDS/Collision_Prediction#49]
Week 3: Tuesday Nov 30.
Review Final report and ReadMe - Daniel
Add report link - Doris
Other scoring metrics on train data
Optimizing accuracy vs f1?
Threshold ROC curve
Milestone 1 feedback - LG
Create ‘make’ file - Moid
Open issue in MDS review - Daniel

**Comment by danfke** [comment]
Ended up optimizing with f1. Didn't do the threshold curve because the low average precision I was obtaining from the models did not make it seem worth it.

**Comment by danfke** [comment]
Now that I've edited the data and model related scripts once we merge my pull requests, slight edits will have to be done on the EDA script to get it to work.

**Comment by danfke** [comment]
The makefile will also have to be edited because I changed the tables used.

**Comment by iamMoid** [comment]
RScript dependencies: tidyverse_1.3.1  kableExtra_1.3.4 knitr_1.36

**Comment by iamMoid** [comment]
Make version: GNU Make 4.3

**Comment by danfke** [comment]
As mentioned by @gfairbro there is a problem with rendering png from altair on certain windows machines. 

```The environment is missing something for the EDA in windows. I know this because our project is too! in order to output PNG in windows from altair you need to run the following, and it doesnt seem to get captured properly when you export a environment.yaml file:
npm install -g vega vega-cli vega-lite canvas
(see lecture 2 from 531 for details - scroll down to the warning):
https://pages.github.ubc.ca/mds-2021-22/DSCI_531_viz-1_students/lectures/2-data-types_graphical-marks_visual-encondings.html#global-development-data```

Not really sure how to implement this if it doesnt work by putting it in the environment file. I'm mostly worried that if a TA happens to have a computer where it won't render then we will lose marks because they can't reproduce our project.
