### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/Collision_Prediction#59]
- [ ] Write your own Dockerfile (this should include all the software and libraries/packages needed to run your analysis pipeline, but not this project itself - i.e., do not git clone your project repo inside your Dockerfile). This Dockerfile should live in the root of your project repository.
- [ ] Use GitHub Actions to build your Docker image from your Dockerfile. Do NOT include any of your data or code in the docker images!
- [ ] Include instructions in the project README on how to use your project with and without Docker.

**Comment by gn385x** [comment]
hey @SiqiTao! according to my understanding, there are two main parts that need to get done here:

1. Write Dockerfile
2. Build Docker image from Dockerfile

I have been reviewing all lecture videos/ notes tonight to get a sense of Docker. So I have been trying to do part 1 - write Dockerfile. There are still many uncertainties so I will need to consult TA during lab tomorrow to finish the Dockerfile. Can you be in charge of part 2 - build Docker image then? At the same time, we can ask @danfke and @iamMoid for help as well! Tbh I'm still quite lost now lol.

**Comment by SiqiTao** [comment]
lol I was trying to write the first part as well but yes I will look into the second part later! I am so confused too hahaha

**Comment by iamMoid** [comment]
I would suggest following the slack channel for 522 to be aware of the challenges others are facing.

**Comment by iamMoid** [comment]
Based on my observations, it is difficult to install R packages on a docker image that is based on Python. However, the `jupyter/datascience-notebook` docker file supports both! Here is an example that @ttimbers suggested on slack: https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile which can serve as a good starting point.

**Comment by gn385x** [comment]
Sooooo finally, the Dockerfile run smoothly, and I was able to run Makefile successfully with this Dockerfile. 
@SiqiTao it's ready for you to take over. thank you!!
