### ISSUE TITLE
Project Proposal (README.md)

### ISSUE THREAD

**Issue by danfke** [UBC-MDS/Collision_Prediction#7]

**Comment by danfke** [comment]
Rough outline:

Research question: “Will a car crash result in fatalities?”. Sub-questions: 
	Methodological:
“What features are relevant? Should simplify.”
“What model would perform best?”
“Which hyperparameters are best?”
“How will we deal with missing values?”
	Research:
What are the characteristics that lead to a severe car crash?
Weather
Road type
Time of year
Age of driver
Vehicle type
3. Try different classification models, tune hyperparameters, pick the best performing one.

4. We will use .info() and .describe() for EDA tables and overlapping histograms for numeric features separated by class value.
5. Table of scoring metrics.

**Comment by gn385x** [comment]
Hey Daniel, I reviewed your proposal and added a few comments (minor ones). Otherwise, all look good to me. Thank you!
